### ISSUE TITLE
Contador de tiempo desde el 2025

### ISSUE THREAD

**Issue by livan23l** [livan23l/deseos2025#19]
Necesitamos crear de forma independiente los componentes que tendrá la página web.

- [x] Crea un archivo llamado `cuenta-regresiva-final.html`

Ahí vas a crear una plantilla para la cuenta regresiva cuando esta ya haya sido finalizada, es decir, cuando ya sea 2025 (se espera que solo se vea la plantilla, no es necesario que agregues nada más)

- [x] Agregar al archivo que acabas de crear el archivo normalize.css
- [x] Agregar una sección donde se verán los días, horas, minutos y segundos que han pasado desde el 2025 (pon el texto: 'DD:HH:MM:SS')
- [x] Agrega un gif de fuegos artificiales que sea PNG.
- [x] Agrega los estilos necesarios en el archivo style.css, asegúrate de reutilizar lo necesario del contador que ya existe.

**Comment by AlonsoCanales-Prog** [comment]
Las 5 tasks de esta issue han sido completadas, esperando a revisión.
