### ISSUE TITLE
Sección para ver una previa vista de la carta de año nuevo

### ISSUE THREAD

**Issue by livan23l** [livan23l/deseos2025#34]
Es necesario crear una sección para ver la carta de año nuevo que creen los usuarios. Para esto deberás hacer lo siguiente

- [x] Crea un archivo llamado `carta.html` al cuál le agregarás los archivos `normalize.css` y `style.css`
- [x] Agrega al archivo las secciones de header y footer que ya existen en el resto de archivos, además de agregar una sección main donde pondrás el contenido
- [x] Aquí deberás poner la imagen que se adjunta en este ISSUE como contenido principal (luego se modificará por el div con la carta)
- [x] Posteriormente deberás poner dos botones, uno que diga "Descargar carta" y otro para volver al formulario de creación (tú dale el nombre que consideres a este segundo botón).
- [x] Dale estilos para que no quede todo demasiado grande, puedes reutilizar los estilos que ya existan

![Carta](https://github.com/user-attachments/assets/69536fa8-af9a-427c-b794-89081cddaef8)

**Comment by AlonsoCanales-Prog** [comment]
Las 5 tasks de esta issue han sido completadas.
