### ISSUE TITLE
Crear un header

### ISSUE THREAD

**Issue by livan23l** [livan23l/deseos2025#4]
Necesitamos crear de forma independiente los componentes que tendrá la página web.

- [x] Crea un archivo llamado `header.html` con la estructura básica de un HTML.

En ese archivo crearás el header que vamos a utilizar en todo el sitio web. Para esto deberás realizar distintas tareas:

- [x] Define en el archivo `style.css` dos variables, una llamada `--primario` que contendrá el color de fondo del header y otra llamada `--texto-primario` que llevará el color del texto en el header. Los colores pueden cambiar en un futuro, así que no te preocupes demasiado por ellos. Si necesitas declarar algún color secundario hazlo.
- [x] Crea la estructura del header en el archivo html que creaste. El header tendrá etiquetas `<h1></h1>` para el título de la página ("Deseos 2025") y un menú de navegación con dos opciones, "Generador de carta" y "Cuenta regresiva". Ten en cuenta que para crear este header debes empezar con el diseño para teléfono y luego hacer una media query para pantallas grandes.
- [x] En pantallas chicas se debe ver primero una fila con el título de la página y debajo de esta debe estar el menú de navegación con cada opción también en una fila.
- [x] En pantallas grandes (36rem o más) se necesita que esté todo en una misma fila, con el título a la izquierda y las opciones a la derecha.
- [x] Cuanto más crezca la pantalla más se separarán las opciones entre sí, por ende es necesario que le asignes un tamaño máximo para que no se separen demasiado en pantallas demasiado grandes (el color del header se debe extender por todo el ancho de la pantalla, pero las opciones no deben separarse entre sí más del límite que le pongas)
- [x] Agrega los estilos que necesites en el archivo `style.css`

**Comment by AlonsoCanales-Prog** [comment]
Las 7 tasks de esta Issue han sido completadas, en espera de revisión.
