### ISSUE TITLE
Crear la sección sobre nosotros

### ISSUE THREAD

**Issue by livan23l** [livan23l/deseos2025#5]
Necesitamos crear de forma independiente los componentes que tendrá la página web.

- [x] Crea un archivo llamado `nosotros.html`

En este archivo vamos a poner para qué se creó la página. **Solamente se espera** que pongas la sección donde estará la descripción sobre la página, **no debes preocuparte de nada más**.

- [x] Incluye el archivo `normalize.css` a tu página para que los estilos que agregues ya estén normalizados.
- [x] Crea un `<article></article>` con la clase `nosotros` en el archivo que acabas de crear.
- [x] Debes incluir en ese article la información de para qué servirá la página. Invita a los usuarios a generar una carta de año nuevo o a ver cuánto tiempo falta para el año 2025. Menciona todo lo que consideres necesario en la página como que fue creada desde cero por un grupo independiente de desarrolladores, etc. Asegúrate de poner enlaces (vacíos de momento) hacia las secciones de la página.
- [x] Te encargarás de darle estilos a esta clase en el archivo `style.css`. Si necesitas dar estilos a más clases que hayas creado puedes hacerlo también.

**Comment by Zuzuky** [comment]
Se crea el archivo  nosotros.html, se incluye normalize se crea un article con la clase nosotros, darle estilos al archivo style.css
