### ISSUE TITLE
Crear plantilla para la cuenta regresiva

### ISSUE THREAD

**Issue by livan23l** [livan23l/deseos2025#8]
Necesitamos crear de forma independiente los componentes que tendrá la página web.

- [x] Crea un archivo llamado `cuenta-regresiva.html`

Ahí vas a crear una plantilla para la cuenta regresiva (se espera que solo se vea la plantilla, no es necesario que agregues nada más)

- [x] Agregar al archivo que acabas de crear el archivo `normalize.css`
- [x] Agregar una sección donde se verán los días, horas, minutos y segundos faltantes para el 2025 (pon el texto: 'DD:HH:MM:SS')
- [x] Agrega el gif de espera en la página.
- [x] Agrega los estilos necesarios en el archivo `style.css`

**Comment by AlonsoCanales-Prog** [comment]
Se completaron las 5 actividades de esta issue, observació: no encontré el gif que habíamos elegido durante la última sesión, así que se agregó uno muy parecido.
